# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308db668d65be74f90b56268398797191f088fed0b89cfd41a40916510ead843be55e964c80c57009df04f7593519147a7c594d94919c4553f6aa5801874c4fa

test:
  secret_key_base: 589ceeff17870dae33ce202051f9249407043283081893c936fa523b80ad5e8bf4bc1f671e7444100fb5b5502e70b5a9ecd92290d9306f266fab8af5478b2db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
